#!/usr/bin/env bash
# Installs ufw and blocks all incoming traffic except ports 22, 80 and 443
apt-get update
apt-get install -y ufw
ufw default deny incoming
ufw default allow outgoing
ufw allow 22/tcp
ufw allow 443/tcp
ufw allow 80/tcp
ufw --force enable
