#!/usr/bin/env bash
# Fixes the container so Apache returns a page containing Hello Holberton
echo "Hello Holberton" > /var/www/html/index.html
apt-get update
apt-get install -y apache2
service apache2 restart
