#!/usr/bin/env bash
# Configures nginx to listen on port 80 of all active IPv4 IPs
apt-get update
apt-get install -y nginx
printf 'server {\n\tlisten 80 default_server;\n\tlisten [::]:80 default_server;\n\troot /var/www/html;\n\tindex index.html index.htm;\n\tserver_name _;\n\tlocation / {\n\t\ttry_files $uri $uri/ =404;\n\t}\n}\n' > /etc/nginx/sites-available/default
service nginx restart
