#!/usr/bin/env bash
# Configures nginx to listen on port 80 of all active IPv4 IPs
sed -i "s/listen 8080 default_server;/listen 80 default_server;/" /etc/nginx/sites-enabled/default
sed -i "s/listen \[::\]:8080 default_server ipv6only=on;/listen [::]:80 default_server ipv6only=on;/" /etc/nginx/sites-enabled/default
pkill nginx
service nginx start
