#!/usr/bin/env bash
# Installs nginx, configures a 301 redirect and a custom 404 page
apt-get update
apt-get install -y nginx
echo "Holberton School for the win!" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/custom_404.html
sed -i '/server_name _;/a \\n\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;\n\n\terror_page 404 /custom_404.html;\n\tlocation = /custom_404.html {\n\t\troot /var/www/html;\n\t\tinternal;\n\t}' /etc/nginx/sites-available/default
service nginx restart
